#!/bin/bash

podman build \
  --target planar-sysimage \
  --build-arg=COMPILE_SCRIPT=scripts/compile.jl \
  --build-arg=PLANAR_BINANCE_SANDBOX_APIKEY=$PLANAR_BINANCE_SANDBOX_APIKEY \
  --build-arg=PLANAR_BINANCE_SANDBOX_SECRET=$PLANAR_BINANCE_SANDBOX_SECRET \
  --build-arg=PLANAR_BINANCE_SANDBOX_PASSWORD=$PLANAR_BINANCE_SANDBOX_PASSWORD \
  --build-arg=PLANAR_PHEMEX_SANDBOX_APIKEY=$PLANAR_PHEMEX_SANDBOX_APIKEY \
  --build-arg=PLANAR_PHEMEX_SANDBOX_SECRET=$PLANAR_PHEMEX_SANDBOX_SECRET \
  --build-arg=PLANAR_PHEMEX_SANDBOX_PASSWORD=$PLANAR_PHEMEX_SANDBOX_PASSWORD \
  -t planar .
